### ISSUE TITLE
Consider adding a "technologies" multi value field

### ISSUE THREAD

**Issue by giosce** [publiccodeyml/publiccode.yml#100]
Many open source civic tech catalogs include search by technology (like java or sql or nodejs, etc.). I'd make it mandatory if possible, from a developer potential contributor this is an important information.

**Comment by lsmith77** [comment]
Both this issue and #89 (multiple `softwareType` values) are asking for the same thing from different angles. Rather than adding `technologies` as a standalone field, I'd suggest solving both at once with a faceted `classification` section based on the [OSS Taxonomy](https://nesbitt.io/2025/11/29/oss-taxonomy.html):

```yaml
classification:
  technology: [php, postgresql] # this issue
  role: [framework, platform] # replaces softwareType, supports multiple values (#89)
  domain: [content-management]
  function: [authentication, crm]
```

More detail in [this proposal](https://github.com/lsmith77/open-source-ecosystem/blob/main/PROPOSAL.md#improvement-1-faceted-classification-replacing-flat-categories). Happy to write up a formal proposal if there's appetite for it.
