### ISSUE TITLE
Specify or document a way to retrieve `softwareVersion` from elsewhere

### ISSUE THREAD

**Issue by christophehenry** [publiccodeyml/publiccode.yml#196]
Project version is often already specified in somewhere in a a project file. For python projects, for instance, it may be `setup.py`, `setup.cfg`, `pyproject.toml` or `version.py`. The [`pyproject.toml`](https://packaging.python.org/en/latest/guides/single-sourcing-package-version/#single-sourcing-the-version) standard, offers the `attr: package.__version__` syntax for sourcing from a python file.

`publiccodeyml` should offer a similar feature. `softwareVersion` could be extended to be used like this:

```yml
softwareVersion:
  file: pyproject.toml
  search: 'version\s+=\s+"(?P<version>[^"]+)"'
```

Maybe something simpler that regexes can be found, IDK.
