### ISSUE TITLE
Make screenshots accessible

### ISSUE THREAD

**Issue by hexabinaer** [publiccodeyml/publiccode.yml#207]
Don't know if there might be constraints ... but shouldn't images be accessible for screenreaders? 

Nice to have (really nice): Attribution

Thinking along those lines:

```
[lang]:
  screenshots:
    - url: ...
      alt: "Description of what's visible in screenthot"
      attributionUrl: https://creativecommons.org/licenses/by-sa/4.0/
      attributionName: "Awesome Creator"
    - url: ...
      alt: ...
```
